#!/usr/bin/env bash
# awk and bas function
subdomain="$2"
domain="$1"
subdomain_list=("www" "lb-01" "web-01" "web-02")

print_fun () {
    dig_cmd=$(dig $sub.$domain | grep -A1 'ANSWER SECTION:' | cut -d':' -f2-)
    record=$(echo $dig_cmd | awk '{print $4}')
    ip_add=$(echo $dig_cmd | awk '{print $5}')
    echo "The subdomain $sub is a $record record and points to $ip_add"
    return 0
}

if [ -z "$subdomain" ]
then
   for sub in "${subdomain_list[@]}"
   do
       dig_func "$domain" sub
   done
else
    sub=$subdomain
    dig_func "$domain" "$sub"
fi
exit 0
