#!/usr/bin/env bash
#install ngix and put holberton inside
301="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i 301" /etc/nginx/sites-available/default
sudo service nginx start
