#!/usr/bin/env bash
#install ngix and put holberton inside
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
301="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "s/listen 80 default_server;/$301/" /etc/nginx/sites-enabled/default
sudo service nginx start
