#!/usr/bin/env bash
#install ngix and put holberton inside
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "35i\     add_header X-Served-By $HOSTNAME ;" /etc/nginx/sites-enabled/default
sudo service nginx start
