#!/usr/bin/env bash
#more toy story message
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rm -f '/var/run/holbertonscript.pid'; exit" SIGTERM
trap "echo 'I hate the kill command'; rm -f '/var/run/holbertonscript.pid'; exit" SIGQUIT
echo $$ >> /var/run/holbertonscript.pid
while true
do
    echo "to infinity and beyond"
    sleep 2
done
