#!/usr/bin/env bash
#this script use the while loop and if state
a=1
while [ $a -le 10 ]
do
    if [ $a -eq 4 ]; then
	echo "bad luck"
    elif [ $a -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let a=a+1
done 
